name: Deploy to Server

on:
  push:
    branches:
      - main  # Change if you're using a different branch for production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Match your project's Node version

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 139.59.79.169  # Your server IP address
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/password-manager/frontend
          git pull origin main
          npm install
          npm run build
          sudo systemctl restart nginx
