name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DO_SSH_KEY }}

    - name: Deploy to DigitalOcean
      run: |
        ssh -o StrictHostKeyChecking=no root@139.59.79.169 << 'EOF'
          cd /var/www/password-manager/frontend
          git pull origin main
          npm install --production
          npm run build
          systemctl restart nginx
        EOF
